/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ApiFetchImageRouteImport } from './routes/api/fetch-image'
import { Route as ApiRuntimeRouteImport } from './routes/api/runtime'
import { Route as ApiRuntimeTicketRouteImport } from './routes/api/runtime-ticket'
import { Route as PIdRouteImport } from './routes/p/$id'
import { Route as ApiRtPortSplatRouteImport } from './routes/api/rt/$port/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchImageRoute = ApiFetchImageRouteImport.update({
  id: '/api/fetch-image',
  path: '/api/fetch-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeRoute = ApiRuntimeRouteImport.update({
  id: '/api/runtime',
  path: '/api/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeTicketRoute = ApiRuntimeTicketRouteImport.update({
  id: '/api/runtime-ticket',
  path: '/api/runtime-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtPortSplatRoute = ApiRtPortSplatRouteImport.update({
  id: '/api/rt/$port/$',
  path: '/api/rt/$port/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/fetch-image': typeof ApiFetchImageRoute
  '/api/runtime': typeof ApiRuntimeRoute
  '/api/runtime-ticket': typeof ApiRuntimeTicketRoute
  '/p/$id': typeof PIdRoute
  '/api/rt/$port/$': typeof ApiRtPortSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/fetch-image': typeof ApiFetchImageRoute
  '/api/runtime': typeof ApiRuntimeRoute
  '/api/runtime-ticket': typeof ApiRuntimeTicketRoute
  '/p/$id': typeof PIdRoute
  '/api/rt/$port/$': typeof ApiRtPortSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/fetch-image': typeof ApiFetchImageRoute
  '/api/runtime': typeof ApiRuntimeRoute
  '/api/runtime-ticket': typeof ApiRuntimeTicketRoute
  '/p/$id': typeof PIdRoute
  '/api/rt/$port/$': typeof ApiRtPortSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/projects'
    | '/api/agent'
    | '/api/fetch-image'
    | '/api/runtime'
    | '/api/runtime-ticket'
    | '/p/$id'
    | '/api/rt/$port/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/projects'
    | '/api/agent'
    | '/api/fetch-image'
    | '/api/runtime'
    | '/api/runtime-ticket'
    | '/p/$id'
    | '/api/rt/$port/$'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/projects'
    | '/api/agent'
    | '/api/fetch-image'
    | '/api/runtime'
    | '/api/runtime-ticket'
    | '/p/$id'
    | '/api/rt/$port/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProjectsRoute: typeof ProjectsRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiFetchImageRoute: typeof ApiFetchImageRoute
  ApiRuntimeRoute: typeof ApiRuntimeRoute
  ApiRuntimeTicketRoute: typeof ApiRuntimeTicketRoute
  PIdRoute: typeof PIdRoute
  ApiRtPortSplatRoute: typeof ApiRtPortSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-image': {
      id: '/api/fetch-image'
      path: '/api/fetch-image'
      fullPath: '/api/fetch-image'
      preLoaderRoute: typeof ApiFetchImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime': {
      id: '/api/runtime'
      path: '/api/runtime'
      fullPath: '/api/runtime'
      preLoaderRoute: typeof ApiRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime-ticket': {
      id: '/api/runtime-ticket'
      path: '/api/runtime-ticket'
      fullPath: '/api/runtime-ticket'
      preLoaderRoute: typeof ApiRuntimeTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rt/$port/$': {
      id: '/api/rt/$port/$'
      path: '/api/rt/$port/$'
      fullPath: '/api/rt/$port/$'
      preLoaderRoute: typeof ApiRtPortSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProjectsRoute: ProjectsRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiFetchImageRoute: ApiFetchImageRoute,
  ApiRuntimeRoute: ApiRuntimeRoute,
  ApiRuntimeTicketRoute: ApiRuntimeTicketRoute,
  PIdRoute: PIdRoute,
  ApiRtPortSplatRoute: ApiRtPortSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
